#!/bin/bash

current_profile=$(powerprofilesctl get)

if [ "$current_profile" == "performance" ]; then
    powerprofilesctl set balanced
elif [ "$current_profile" == "balanced" ]; then
    powerprofilesctl set power-saver
else
    powerprofilesctl set performance
fi
