#!/bin/bash

# Get battery status and percentage
battery_info=$(acpi -b)
battery_status=$(echo "$battery_info" | awk '{print $3}')
battery_percentage=$(echo "$battery_info" | awk -F, '{print $2}' | tr -d '%')

# Determine the battery icon based on the status
if [ "$battery_status" == "Discharging," ]; then
    battery_icon="BAT"
    color="#FFFFFF"  # White color while discharging
elif [ "$battery_status" == "Charging," ]; then
    battery_icon="CHR"
    color="#00FF00"  # Green color while charging
else
    battery_icon="BAT"
    battery_icon="<span><span color='#FFA500'>[</span>Full<span color='#FFA500'>]</span></span>"
    color="#ff52dc"  # Default color
fi

# Function to get the current profile color
get_profile_color() {
    profile=$1
    case $profile in
        "performance")
            echo "#ff4ad5"
            ;;
        "balanced")
            echo "#dfff40"
            ;;
        "power-saver")
            echo "#00FF00"
            ;;
        *)
            echo "#FFFFFF"
            ;;
    esac
}

# Get the current power profile
current_profile=$(powerprofilesctl get)

# Handle mouse click events
if [ "$BLOCK_BUTTON" == "1" ]; then
    if [ "$current_profile" == "performance" ]; then
        powerprofilesctl set balanced
    elif [ "$current_profile" == "balanced" ]; then
        powerprofilesctl set power-saver
    else
        powerprofilesctl set performance
    fi
    # Get the updated power profile after change
    current_profile=$(powerprofilesctl get)
fi

# Get the color for the current profile
color1=$(get_profile_color "$current_profile")

# Output the battery icon, percentage, and current power profile with appropriate color
echo "<span foreground='$color'>$battery_icon <span color='#00FF00'>$battery_percentage% </span><span foreground='$color1'><span color='#FFA500'>[</span>$current_profile<span color='#FFA500'>]</span></span></span>"
